### ISSUE TITLE
Resource data is unused

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [honeycombio/opentelemetry-exporter-python#16]
Whereas other OTel concepts like span links and span events are "used" (both become events sent to Honeycomb), the OTel concept of [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/v0.7.0/specification/resource/sdk.md) is unsupported as of opentelemetry-ext-honeycomb==0.15b1.

Resource attributes can contain useful info, info which in the OTel model ought not be on spans directly. E.g., here's an example from a Google App Engine service, following OTel's [semantic conventions for resource attributes](https://github.com/open-telemetry/opentelemetry-specification/tree/v0.7.0/specification/resource/semantic_conventions):
```json
{
  "telemetry.sdk.language": "python",
  "telemetry.sdk.name": "opentelemetry",
  "telemetry.sdk.version": "0.15b0",
  "cloud.provider": "gcp",
  "cloud.zone": "us16",
  "cloud.account.id": "<redacted>",
  "service.name": "default",
  "service.instance.id": "00c61b117c1f0a41f141a889024a26ef4d3474c9bf28da9ff2a36f1d9c51c1b81ac3fd700026dcd00ee47c4a9e395bb59188cd6fdb969619cbd38afb6d5cddf9e9470d85127b5f",
  "service.version": "cb-pr-13615",
  "gae.version": "1.9.71"
}
```

Proposal: Update the exporter to merge resource attributes—`span.resource.attributes`, currently a `Dict[str, Union[str, bool, int, float]]`—into event fields.

Risks:

1. Clobbering same-named span attributes that the instrumentation set directly on the span. If this can't be explained with docs and is deemed unacceptable, maybe add a `resource.` prefix to attribute names before merging them into the span's attributes?

I personally don't view (1) as unacceptable, but that's up to y'all.

Workaround: Users can add these attributes to the span instead of, or in addition to, the attached resource. That could cause issues though with duplicate data, if e.g. some exporters _do_ do something with the span's Resource. So it's not ideal. Ideally every exporter does something reasonable with each span's Resource.

**Comment by nathanleclaire** [comment]
That's cool, I didn't even know about Resource yet, thanks for the tip off.

Will surface the feedback with the team.
