### ISSUE TITLE
Unwrap Session.send and update requests auto-instrumentation attribute

### ISSUE THREAD

**Issue by melissafritcher** [honeycombio/opentelemetry-exporter-python#27]
The opentel python contrib requests auto instrumentation library recently changed the attribute that was being set to indicate if the requests library was instrumented. They also added instrumentation to the Session.send function.

See this commit for details: https://github.com/open-telemetry/opentelemetry-python-contrib/commit/fbd782c7f48d1dc5f7577a1b681d842f94d17e77

This change is causing spans for posts to the Honeycomb API to be generated and sent, which is causing some background noise.

**Comment by vreynolds** [comment]
Released in https://github.com/honeycombio/opentelemetry-exporter-python/releases/tag/v0.16b0
