### ISSUE TITLE
spans not transmitted without delay at end of program

### ISSUE THREAD

**Issue by DrMcTaco** [honeycombio/opentelemetry-exporter-python#4]
When using this exporter in a process where a parent span finishes simultaneously with process completion a `sleep()` is required to ensure that all spans a re transmitted to honeycomb.

The following is a modified demo open-telemetry implementation where this issue is present:
```python
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchExportSpanProcessor
from opentelemetry.ext.honeycomb import HoneycombSpanExporter

trace.set_tracer_provider(TracerProvider())

honeycomb_exporter = HoneycombSpanExporter(service_name="test-service")

trace.get_tracer_provider().add_span_processor(
    BatchExportSpanProcessor(honeycomb_exporter)
)

tracer = trace.get_tracer(__name__)

with tracer.start_as_current_span("foo"):
    with tracer.start_as_current_span("bar"):
        with tracer.start_as_current_span("baz"):
            print("Hello world from OpenTelemetry Python!")
```
The above behaves identically for the `BatchExportSpanProcessor` and `SimpleExportSpanProcessor`.
Adding a `sleep(6)` as a final operation outside the scope of all the spans seems to allow enough time for the queued spans to be correctly transmitted. 

Attempts to explicitly close and flush the buffers with `libhoney.close()` do not seem to be effective.

**Comment by lizthegrey** [comment]
Thanks for the report! Are you shutting down BatchExport span processor?

`tracer_provider.shutdown()`

https://github.com/open-telemetry/opentelemetry-python/blob/b085f376e0b0bd1c76e8ff4e3f09e995927f7311/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L86

**Comment by DrMcTaco** [comment]
not explicitly, but I believe the TracerProvider registers the `shutdown` method as an `atexit` handler on instantiation:

https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L875

**Comment by DrMcTaco** [comment]
explicitly getting the provider and calling its shutdown method seems to do the trick. 
```pyhton
trace.get_tracer_provider().shutdown()
```

Potentially some disconnect with the at exit handlers, but no issue with this exporter. I will close this issue.

**Comment by lizthegrey** [comment]
Yup, please file this with OpenTelemetry Python SDK then, thanks!
